### PR TITLE
Added GitHub Workflow for Automated Testing with pytest

### PR DESCRIPTION
**Pull request by alirashidAR**
# Pull Request

## Description

Added a GitHub workflow file (pytest.yml) under .github/workflows to automate testing for the implemented features using pytest.(Part of #7 )

## How Has This Been Tested?

- [x] Yes

The GitHub workflow has been tested and works as expected. The workflow successfully ran the tests without errors.

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by alirashidAR** [comment]
Hi @peterdudfield,

I have a quick question regarding the release workflow. Since some development is still in progress, do you think it would be best to hold off on adding the release workflow for now, or should I proceed with setting it up?

**Comment by peterdudfield** [comment]
Yea, let's hold fire on the release workflow. Perhaps a separate pr and then it's ready to go

**Comment by alirashidAR** [comment]
Sure! The testing CI seems to be working fine. I’m happy for this to be merged—let me know if there are any changes you’d like me to make!

**Review by peterdudfield — APPROVED** [review]

**Comment by peterdudfield** [comment]
@all-contributors please add @alirashidAR  for test

**Pull request merged**
